dist: trusty
language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'
  - nightly
  - hhvm
  - hhvm-3.18
  - hhvm-nightly

matrix:
  allow_failures:
    - php: nightly
    - php: hhvm
    - php: hhvm-nightly

cache:
  directories:
    - $HOME/.composer/cache/files

before_script:
  - travis_wait 30 composer install --no-interaction

script:
  - composer run check

jobs:
  include:
    - stage: report
      php: 5.6
      script: php vendor/bin/php-coveralls -v

sudo: false
