language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - nightly
  - hhvm
  - hhvm-3.18
  - hhvm-nightly

matrix:
  allow_failures:
    - php: nightly
    - php: hhvm
    - php: hhvm-nightly

cache:
  directories:
    - $HOME/.composer/cache/files

before_script:
  - travis_wait 30 composer install --no-interaction
  - [ ! -z "$CREDENTIALS" ] && echo $CREDENTIALS > credentials1.json || echo "Credentials not found. Skipping integration tests."[ ! -z "$CREDENTIALS" ] && echo $CREDENTIALS > credentials1.json || echo "Credentials not found. Skipping integration tests."

script:
  - composer run check

after_script:
  - php vendor/bin/php-coveralls -v

sudo: false
